In [ ]:
#@title 

%%HTML
<div style="text-align:center; display:flex; justify-content:space-between;">
<div style="background-color:white; width:25%; height:150px; display: flex;">

<img src="https://giecaruff.github.io/sites/gss_semana_2020/logos/GSS_semana_geofisica.png" height="40%">

</div>
<div style="background-color:white; width:50%; height:150px; text-align:center;">

<br><br>

<span style="color:purple; font-size: 16pt;">Semana acadêmica virtual 2020 <br></span>
<span style="color:purple; font-size: 25pt;font-weight: bold;">Minicurso Python Para Geofísicos </span>

</div>

<div style="background-color:white; width:25%; height:150px; text-align:right">
<img src="https://giecaruff.github.io/sites/gss_semana_2020/logos/logo_colorida_icone.png" height="60%">
</div>
</div>

<div style="background-color:white">
<center><span style="color:purple; font-size: 25pt;font-weight: bold;center">Equipe:</span>
<br><br>

<div style="background-color:white;width:172px;text-align:center;display:inline-block;"> <span style="color:#92d14f; font-size: 14pt;font-weight: bold;">Fernando Vizeu</span> <div><img src="https://giecaruff.github.io/sites/gss_semana_2020/integrantes/vizeu.jfif" width="150px" style="border-radius:50%;border-style: solid;"></div> <span style="color:#3991c9; font-size: 10pt">fernandovizeu@id.uff.br</span> </div>
<div style="background-color:white;width:172px;text-align:center;display:inline-block;"> <span style="color:#92d14f; font-size: 14pt;font-weight: bold;">Mário Martins</span> <div><img src="https://giecaruff.github.io/sites/gss_semana_2020/integrantes/mario_machine.png" width="150px" style="border-radius:50%;border-style: solid;"></div> <span style="color:#3991c9; font-size: 10pt">mario_martins@id.uff.br</span> </div>
<div style="background-color:white;width:172px;text-align:center;display:inline-block;"> <span style="color:#92d14f; font-size: 14pt;font-weight: bold;">Rodrigo Mota</span> <div><img src="https://giecaruff.github.io/sites/gss_semana_2020/integrantes/rodrigo_dutra.jfif" width="150px" style="border-radius:50%;border-style: solid;"></div> <span style="color:#3991c9; font-size: 10pt">dutrarodrigo@id.uff.br</span> </div>
<div style="background-color:white;width:172px;text-align:center;display:inline-block;"> <span style="color:#92d14f; font-size: 14pt;font-weight: bold;">Rodrigo Bijani</span> <div><img src="https://giecaruff.github.io/sites/gss_semana_2020/integrantes/rodrigo_bijani.jfif" width="150px" style="border-radius:50%;border-style: solid;"></div> <span style="color:#3991c9; font-size: 10pt">rodrigobijani@id.uff.br</span> </div>

</div>

In [ ]:
import numpy as np

# Constantes

doc: [constantes](https://numpy.org/doc/stable/reference/constants)

## `np.nan`

Not a Number(NaN).

> - `np.isnan()`: Verifica se o elemento é NaN.

In [ ]:
print(np.nan, np.NAN, np.NaN)
print(np.isnan(np.nan), np.isnan(3.0))

nan nan nan
True False


## `np.inf`

Infinito positivo.

> - `np.isinf()`: Verifica se o elemento é infinito positivo ou infinito negativo.
> - `np.isposinf()`: Verifica se o elemento é infinito positivo.

In [ ]:
print(np.inf, np.Infinity, np.PINF, np.infty)
print(np.isinf(np.inf), np.isposinf(np.inf), np.isinf(2.0))

inf inf inf inf
True True False


## `np.NINF`

Infinito negativo.

> - `np.isneginf()`: Verifica se o elemento é infinito negativo.

In [ ]:
print(np.NINF)
print(np.isneginf(np.NINF), np.isneginf(2.0))

-inf
True False


Obs:

> - `np.isfinite()`: Verifica se o elemento é finito, ou seja, não é NaN, nem infinito positivo, nem infinito negativo.

In [ ]:
print(np.isfinite(np.nan), np.isfinite(np.inf), np.isfinite(np.NINF), np.isfinite(5))

False False False True


# Arrays

## `np.linspace(start, stop, num=50)`

Cria um array com elementos igualmente espaçados.

> - `start:` Valor inicial do array.
> - `stop:` Valor final do array.
> - `num:` Quantidade de amostras do array. Padrão é 50.

doc: [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace)

In [ ]:
linspace = np.linspace(3, 20, num=5)
print(linspace)

[ 3.    7.25 11.5  15.75 20.  ]


## `np.logspace(start, stop, num=50)`

Cria um array com elementos espaçados em escala log.

> - `start:` Valor inicial do array.
> - `stop:` Valor final do array.
> - `num:` Quantidade de amostras do array. Padrão é 50.

doc: [np.logspace](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html#numpy.logspace)

In [ ]:
logspace = np.logspace(2, 15, num=5)
print(logspace)

[1.00000000e+02 1.77827941e+05 3.16227766e+08 5.62341325e+11
 1.00000000e+15]


## `np.arange(start, stop, step)`

Cria um array com elementos igualmente espaçados, com tamanho do espaço igual ao *step*.

> - `start:` Valor inicial do array. Padrão é 0.
> - `stop:` Valor final do array.
> - `step:` Tamanho do espaço entre valores adjacentes.

doc: [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange)



In [ ]:
arange = np.arange(3, 15, 2)
print(arange)

[ 3  5  7  9 11 13]


## `np.zeros(shape)`

Cria um array de acordo com o tamanho informado, preenchido com zeros.

> - `shape:` Tamanho do array.

doc: [np.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zeros#numpy.zeros)

In [ ]:
zeros = np.zeros(5)
print(zeros)
zeros = np.zeros((3,3))
print(zeros)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## `np.ones(shape)`

Cria um array de acordo com o tamanho informado, preenchido com uns.

> - `shape:` Tamanho do array.

doc: [np.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)

In [ ]:
ones = np.ones(3)
print(ones)
ones = np.ones((3,3))
print(ones)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## `np.empty(shape)`

Cria um array de acordo com o tamanho informado, sem inicializar as entradas.

> - `shape:` Tamanho do array.

doc: [np.empty](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty)

In [ ]:
empty = np.empty(5)
print(empty)
empty = np.empty((3,3))
print(empty)

[3.5 3.5 3.5 3.5 3.5]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## `np.full(shape, value)`

Cria um array de acordo com o tamanho informado, preenchido com o valor informado.

> - `shape:` Tamanho do array.
> - `value:` Valor a ser preenchido.

doc: [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full)

In [ ]:
full = np.full(5, 3.5)
print(full)
full = np.full(5, np.nan)
print(full)

[3.5 3.5 3.5 3.5 3.5]
[nan nan nan nan nan]


# Aleatórios

## `np.random.rand(shape)`

Cria um array de acordo com o tamanho informado, preenchido com valores aleatórios a partir de um distribuição uniforme entre [0, 1).

> - `shape:` Tamanho do array.

docs: [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=random%20rand#numpy.random.rand)

In [35]:
rand = np.random.rand(5,2)
print(rand)

[[0.93222738 0.16316297]
 [0.15572121 0.12153685]
 [0.24615557 0.4857687 ]
 [0.20624581 0.74354338]
 [0.01297754 0.32775135]]


## `np.random.randn(shape)`

Cria um array de acordo com o tamanho informado, preenchido com valores aleatórios a partir de um distribuição normal (gaussiana) de média 0 e desvio padrão 1.

> - `shape:` Tamanho do array.

docs: [np.random.randn](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html?highlight=random%20randn#numpy.random.randn)

In [37]:
randn = np.random.randn(5,2)
print(randn)

[[-0.81139544 -0.30047931]
 [ 0.10653529  1.93206682]
 [ 1.35248581  0.37716895]
 [-1.64597104  1.20546414]
 [ 1.5509745  -1.00096253]]


## `np.random.choice(a, size=None)`

Gera uma amostra aleatória de um array informado

> - `a:` Array.
> - `size:` Dimensão da saída. Padrão é `None`

doc: [np.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html?highlight=random%20choice#numpy.random.choice)

In [44]:
choice = np.random.choice(np.array([2.0, 3.0, 1.0, 5.0, 0.5]))
print(choice)
choice = np.random.choice(np.array([2.0, 3.0, 1.0, 5.0, 0.5]), 3)
print(choice)
choice = np.random.choice(np.array([2.0, 3.0, 1.0, 5.0, 0.5]), (3,2))
print(choice)

0.5
[0.5 0.5 1. ]
[[5. 5.]
 [1. 2.]
 [2. 1.]]


## `np.random.permutation(x)`

Permuta uma sequência (x) informada.

> - `x:` Sequência.

doc: [np.random.permutation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html#numpy.random.permutation)

In [46]:
permutation = np.random.permutation(10)
print(permutation)
permutation = np.random.permutation([1, 3, 4, 2, 6, 10, 9])
print(permutation)

[4 9 3 2 0 5 1 8 6 7]
[10  4  2  9  1  6  3]


## `np.random.suffle(x)`

Embaralha uma sequência (x) informada.

> - `x:` Sequência.

doc: [np.random.suffle](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html#numpy.random.shuffle)

In [54]:
shuffle = np.arange(10)
print(shuffle)
np.random.shuffle(shuffle)
print(shuffle)

[0 1 2 3 4 5 6 7 8 9]
[8 4 3 1 0 6 9 2 5 7]


In [55]:
# Matrizes só são embaralhadas ao longo das eixo vertical (troca de linhas)
randn = np.random.randn(3,2)
print(randn)
np.random.shuffle(randn)
print(randn)

[[ 0.03180969 -0.65818955]
 [-0.64849563  1.44331932]
 [-0.74637995 -0.24333306]]
[[ 0.03180969 -0.65818955]
 [-0.74637995 -0.24333306]
 [-0.64849563  1.44331932]]
